[package]
name = "bgpstream"
version = "0.2.3"
authors = ["Benjamin VanderSloot <admin@benvds.com>"]

[dependencies]
bgpstream-sys = { git = "https://github.com/bvandersloot/bgpstream-sys" } 
ffi = "*"
num-traits = "0.2"
num-derive = "0.2"
